apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-a
resources:
  - deployment.yml
  - service.yml
images:
  - name: cowmin/project-a-frontend
    newTag: "8789936dd5798eb30af3a58e50af1ab4cbfb479e"
