apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-a
resources:
  - deployment.yml
  - service.yml
images:
  - name: cowmin/project-a-frontend
    newTag: "30ffade44ffbbeb8ce7288d7fb64cbb4efcd4e65"
