apiVersion: v1
kind: Service
metadata:
  name: project-a-frontend
  namespace: project-a
  labels:
    app: project-a-frontend
spec:
  type: ClusterIP
  selector:
    app: project-a-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80