apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-a
resources:
  - rollout.yml
  - service-stable.yml
  - service-canary.yml
images:
  - name: cowmin/project-a-backend
    newTag: "c5c271a24e50cdbaa9a8845c9fb6a099343d392b"
