apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-a
resources:
  - rollout-bluegreen.yml
  - service-active.yml
  - service-preview.yml
images:
  - name: cowmin/project-a-backend
    newTag: "65e33672734486f635213407f827f9fb957afc80"
