apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-a
resources:
  - rollout.yml
  - service-stable.yml
  - service-canary.yml
images:
  - name: cowmin/project-a-backend
    newTag: "635759903596f0a4021925a8cbdd954a20c14f46"
